-- Repara encoding corrupto (U+FFFD) en definiciones_indicadores.nombre.
-- Los caracteres acentuados (á, é, í, ó, ú, ñ, Í) se perdieron al importar datos;
-- este script restaura los 64 nombres afectados con el texto correcto en UTF-8.

UPDATE public.definiciones_indicadores SET nombre = 'Volumen de inversión privada en startups tecnológicas' WHERE id = 1;
UPDATE public.definiciones_indicadores SET nombre = 'Acceso a financiación digital' WHERE id = 2;
UPDATE public.definiciones_indicadores SET nombre = 'Volumen de inversión de capital riesgo en empresas digitales' WHERE id = 3;
UPDATE public.definiciones_indicadores SET nombre = 'Tasa de supervivencia de startups a 3 y 5 años' WHERE id = 5;
UPDATE public.definiciones_indicadores SET nombre = 'Número de startups digitales creadas por año' WHERE id = 6;
UPDATE public.definiciones_indicadores SET nombre = 'Nº de hubs tecnológicos y aceleradoras de startups activas' WHERE id = 8;
UPDATE public.definiciones_indicadores SET nombre = 'Presencia de ecosistemas de emprendimiento e innovación en el territorio' WHERE id = 9;
UPDATE public.definiciones_indicadores SET nombre = 'Programas públicos de apoyo a la digitalización' WHERE id = 10;
UPDATE public.definiciones_indicadores SET nombre = 'Inversión pública en programas de digitalización' WHERE id = 11;
UPDATE public.definiciones_indicadores SET nombre = 'Personas con habilidades digitales básicas' WHERE id = 12;
UPDATE public.definiciones_indicadores SET nombre = 'Personas con habilidades digitales generales superiores a las básicas' WHERE id = 13;
UPDATE public.definiciones_indicadores SET nombre = 'Número de certificaciones y formaciones en competencias digitales' WHERE id = 16;
UPDATE public.definiciones_indicadores SET nombre = '% de empleados que han recibido formación digital en el último año' WHERE id = 17;
UPDATE public.definiciones_indicadores SET nombre = 'Gasto medio por empresa en formación TIC' WHERE id = 18;
UPDATE public.definiciones_indicadores SET nombre = 'Nº de programas de recualificación digital activos' WHERE id = 19;
UPDATE public.definiciones_indicadores SET nombre = '"% de trabajadores que acceden a certificaciones online (MOOC, formación formal)"' WHERE id = 20;
UPDATE public.definiciones_indicadores SET nombre = '% de empresas que promueven formación digital interna' WHERE id = 21;
UPDATE public.definiciones_indicadores SET nombre = 'Crecimiento del empleo en sectores tecnológicos' WHERE id = 23;
UPDATE public.definiciones_indicadores SET nombre = 'Formación en TIC en empresas' WHERE id = 24;
UPDATE public.definiciones_indicadores SET nombre = 'Población con formación en TIC' WHERE id = 25;
UPDATE public.definiciones_indicadores SET nombre = 'Índice de competitividad digital' WHERE id = 27;
UPDATE public.definiciones_indicadores SET nombre = 'Número de eventos regionales anuales de innovación y colaboración digital' WHERE id = 28;
UPDATE public.definiciones_indicadores SET nombre = 'Contribución económica del sector TIC' WHERE id = 30;
UPDATE public.definiciones_indicadores SET nombre = '"% de empresas TIC que participan en clústeres, redes o plataformas digitales"' WHERE id = 31;
UPDATE public.definiciones_indicadores SET nombre = 'Número de acuerdos universidad-empresa en I+D' WHERE id = 32;
UPDATE public.definiciones_indicadores SET nombre = 'Nº de colaboraciones público-privadas en innovación digital' WHERE id = 33;
UPDATE public.definiciones_indicadores SET nombre = 'Presencia en proyectos europeos o consorcios de innovación digital' WHERE id = 34;
UPDATE public.definiciones_indicadores SET nombre = 'Índice de conectividad avanzada (GCI)' WHERE id = 35;
UPDATE public.definiciones_indicadores SET nombre = 'Número de nodos de datos Edge desplegados' WHERE id = 36;
UPDATE public.definiciones_indicadores SET nombre = 'Adopción de banda ancha fija (suscripciones/100 personas)' WHERE id = 39;
UPDATE public.definiciones_indicadores SET nombre = 'Adopción de banda ancha móvil (suscripciones/100 personas)' WHERE id = 40;
UPDATE public.definiciones_indicadores SET nombre = '% de servicios públicos accesibles de forma totalmente digital' WHERE id = 43;
UPDATE public.definiciones_indicadores SET nombre = '% de trámites administrativos que pueden completarse en línea' WHERE id = 44;
UPDATE public.definiciones_indicadores SET nombre = 'Índice de madurez de los servicios públicos digitales' WHERE id = 45;
UPDATE public.definiciones_indicadores SET nombre = 'Inversión pública en TIC por habitante (gasto tecnológico del sector público)' WHERE id = 46;
UPDATE public.definiciones_indicadores SET nombre = 'Personas que interactúan en línea con las autoridades públicas' WHERE id = 47;
UPDATE public.definiciones_indicadores SET nombre = 'Servicios Públicos Digitales para Empresas' WHERE id = 48;
UPDATE public.definiciones_indicadores SET nombre = 'Índice de satisfacción ciudadana con servicios públicos digitales' WHERE id = 50;
UPDATE public.definiciones_indicadores SET nombre = 'Empresas tecnológicas con estrategias de reducción de huella de carbono' WHERE id = 51;
UPDATE public.definiciones_indicadores SET nombre = 'Inversión en economía circular digital' WHERE id = 52;
UPDATE public.definiciones_indicadores SET nombre = 'Uso de TIC para eficiencia energética' WHERE id = 53;
UPDATE public.definiciones_indicadores SET nombre = 'Impacto de la digitalización en reducción de papel' WHERE id = 54;
UPDATE public.definiciones_indicadores SET nombre = 'Empresas preocupadas por el impacto ambiental de decisiones y prácticas digitales' WHERE id = 55;
UPDATE public.definiciones_indicadores SET nombre = 'Consumo energético promedio de las infraestructuras digitales' WHERE id = 56;
UPDATE public.definiciones_indicadores SET nombre = 'Residuos electrónicos gestionados correctamente' WHERE id = 57;
UPDATE public.definiciones_indicadores SET nombre = '% de directivos con formación en transformación digital' WHERE id = 59;
UPDATE public.definiciones_indicadores SET nombre = '% de empresas con responsable de digitalización o CIO' WHERE id = 60;
UPDATE public.definiciones_indicadores SET nombre = 'Índice de apertura al cambio digital' WHERE id = 61;
UPDATE public.definiciones_indicadores SET nombre = '% de empresas que promueven formación continua en TIC' WHERE id = 62;
UPDATE public.definiciones_indicadores SET nombre = 'Empresas que tienen un sitio web o página de inicio' WHERE id = 64;
UPDATE public.definiciones_indicadores SET nombre = 'Empresas que utilizan el mercado de comercio electrónico para ventas' WHERE id = 66;
UPDATE public.definiciones_indicadores SET nombre = 'Volumen de exportación de productos y servicios tecnológicos' WHERE id = 68;
UPDATE public.definiciones_indicadores SET nombre = 'Número de empresas que realizan I+D en el sector TIC' WHERE id = 69;
UPDATE public.definiciones_indicadores SET nombre = 'Número de patentes tecnológicas registradas' WHERE id = 70;
UPDATE public.definiciones_indicadores SET nombre = 'Empresas que comparten información electrónica internamente con un ERP' WHERE id = 71;
UPDATE public.definiciones_indicadores SET nombre = 'Empresas que utilizan software de gestión de relaciones con los clientes (CRM)' WHERE id = 72;
UPDATE public.definiciones_indicadores SET nombre = 'Inversión total en redes del sector de las comunicaciones electrónicas' WHERE id = 76;
UPDATE public.definiciones_indicadores SET nombre = 'Participación de empresas en proyectos de innovación financiados por la UE' WHERE id = 77;
UPDATE public.definiciones_indicadores SET nombre = 'Inversión extranjera en empresas de base tecnológica' WHERE id = 78;
UPDATE public.definiciones_indicadores SET nombre = 'Índice de experimentación empresarial en nuevos modelos digitales' WHERE id = 80;
UPDATE public.definiciones_indicadores SET nombre = 'Índice de Intensidad Digital (DII)' WHERE id = 81;
UPDATE public.definiciones_indicadores SET nombre = 'Nivel de adopción de herramientas digitales en pymes y grandes empresas' WHERE id = 82;
UPDATE public.definiciones_indicadores SET nombre = 'Índice de ciberseguridad en empresas' WHERE id = 83;
UPDATE public.definiciones_indicadores SET nombre = 'Automatización robótica de procesos (RPA)' WHERE id = 84;
