// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfhfwiveuzdnntsmwfib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5maGZ3aXZldXpkbm50c213ZmliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA2ODgxOTYsImV4cCI6MjA5NjI2NDE5Nn0.635V7cld5MXmnw-NEbNso_TXt_K5zNr8DNJNoKRGMb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});